version: '3.8'
services:
  web:
    volumes:
      - ./app:/app
    container_name: corona_de
    networks:
      - public
    ports:
      - 5007:5000
    restart: "unless-stopped"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - TZ=Europe/Berlin
      - 'RUN=flask run --host=0.0.0.0 --port=5000'
    command: flask run --host=0.0.0.0 --port=5000
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"

networks:
  public:
    external: true